export type VideoCategory = 'science' | 'tech' | 'philosophy' | 'math' | 'society' | 'art' | 'history'

export interface MockVideo {
  videoId: string
  title: string
  channel: string
  durationSec: number
  category: VideoCategory
  thumbnailGradient: string
  aiScore: number
  aiReasoning: string
  saved: boolean
  seen: boolean
  seriesId?: string
  season?: number
  episode?: number
  progress?: number // 0 to 1
  dub?: string
}

export interface MockSeries {
  id: string
  title: string
  description: string
  thumbnailGradient: string
  category: VideoCategory
}

export interface MockChannel {
  id: string
  name: string
  handle: string
  subscribers: string
  totalVideos: number
  approved: number
  rejected: number
  diskMB: number
  category: VideoCategory
  accentColor: string
  description: string
  thumbnailGradient?: string
}

export interface MockRejectedVideo {
  videoId: string
  title: string
  channel: string
  durationSec: number
  category: VideoCategory
  thumbnailGradient: string
  aiScore: number
  aiReasoning: string
  clickbaitScore?: number
  manipulationScore?: number
}

export interface SponsorBlockCategory {
  key: string
  label: string
  labelDe: string
  color: string
  defaultBehavior: 'auto' | 'manual' | 'ignore'
  description: string
  exampleSkips: number
  timeSavedMin: number
}

// ─── Feed Videos (15) ────────────────────────────────────────────────────────

export const mockVideos: MockVideo[] = [
  {
    videoId: 'v001',
    title: 'But what is a Neural Network? | Chapter 1',
    channel: '3Blue1Brown',
    durationSec: 1204,
    category: 'math',
    thumbnailGradient: 'from-blue-900 via-indigo-800 to-blue-600',
    aiScore: 97,
    aiReasoning: 'Visuelle Erklärung neuronaler Netze — mathematisch präzise und dabei zugänglich.',
    saved: true,
    seen: true,
    seriesId: 's001',
    season: 1,
    episode: 1,
    progress: 0.9,
  },
  {
    videoId: 'v006',
    title: 'Gradient Descent, how neural networks learn | Chapter 2',
    channel: '3Blue1Brown',
    durationSec: 1552,
    category: 'math',
    thumbnailGradient: 'from-violet-900 via-purple-700 to-indigo-600',
    aiScore: 96,
    aiReasoning: "Eulers Formel geometrisch erklärt.",
    saved: true,
    seen: false,
    seriesId: 's001',
    season: 1,
    episode: 2,
    progress: 0.1,
  },
  {
    videoId: 'v004',
    title: "SpongeBob's Economy: Why Bikini Bottom Is Doomed",
    channel: 'SpongeLore',
    durationSec: 742,
    category: 'society',
    thumbnailGradient: 'from-cyan-500 via-teal-400 to-emerald-500',
    aiScore: 78,
    aiReasoning: 'Überraschend fundierte Wirtschaftsanalyse mit SpongeBob als Einstieg.',
    saved: false,
    seen: false,
    seriesId: 's002',
    season: 1,
    episode: 1,
  },
  {
    videoId: 'v005',
    title: 'Calculus in 20 Minutes — The Intuition Behind Derivatives',
    channel: 'Khan Academy',
    durationSec: 1223,
    category: 'math',
    thumbnailGradient: 'from-green-700 via-emerald-600 to-teal-500',
    aiScore: 89,
    aiReasoning: 'Klare Kalkül-Grundlagen ohne Füllmaterial — pädagogisch präzise.',
    saved: false,
    seen: true,
  },
  {
    videoId: 'v006',
    title: 'This Equation Will Change How You See the World',
    channel: '3Blue1Brown',
    durationSec: 1552,
    category: 'math',
    thumbnailGradient: 'from-violet-900 via-purple-700 to-indigo-600',
    aiScore: 96,
    aiReasoning: "Eulers Formel geometrisch erklärt — hohe mathematische Tiefe als visuelle Poesie.",
    saved: true,
    seen: false,
  },
  {
    videoId: 'v007',
    title: 'The Fermi Paradox — Where Are All The Aliens?',
    channel: 'Kurzgesagt',
    durationSec: 987,
    category: 'science',
    thumbnailGradient: 'from-sky-900 via-blue-800 to-indigo-900',
    aiScore: 88,
    aiReasoning: 'Ausgewogene, quellengestützte Untersuchung des Fermi-Paradoxons — selten für dieses Thema.',
    saved: false,
    seen: true,
  },
  {
    videoId: 'v008',
    title: 'The Problem with Time Zones',
    channel: 'CGP Grey',
    durationSec: 606,
    category: 'society',
    thumbnailGradient: 'from-rose-900 via-red-800 to-orange-700',
    aiScore: 85,
    aiReasoning: 'Prägnante Erklärung eines überraschend komplexen Themas — kein Padding.',
    saved: false,
    seen: false,
  },
  {
    videoId: 'v009',
    title: 'What IS Color? — The Physics and Philosophy of Perception',
    channel: 'Vsauce',
    durationSec: 1320,
    category: 'science',
    thumbnailGradient: 'from-fuchsia-800 via-pink-700 to-rose-600',
    aiScore: 92,
    aiReasoning: 'Optik, Neurowissenschaft und Philosophie produktiv verknüpft — jede Minute verdient ihren Platz.',
    saved: true,
    seen: false,
  },
  {
    videoId: 'v010',
    title: "Why Every Map You've Seen Is Wrong",
    channel: 'CGP Grey',
    durationSec: 518,
    category: 'history',
    thumbnailGradient: 'from-lime-700 via-green-700 to-teal-800',
    aiScore: 83,
    aiReasoning: 'Scharfe Kartographielektion — respektiert die Fähigkeit des Zuschauers, Nuancen zu verarbeiten.',
    saved: false,
    seen: true,
  },
  {
    videoId: 'v011',
    title: 'Spongebob and the Collapse of the Service Economy',
    channel: 'SpongeLore',
    durationSec: 834,
    category: 'society',
    thumbnailGradient: 'from-yellow-600 via-amber-500 to-orange-400',
    aiScore: 76,
    aiReasoning: 'Kreatives soziologisches Objektiv auf Animation — bescheidener Lernwert, aber gut argumentiert.',
    saved: false,
    seen: false,
  },
  {
    videoId: 'v012',
    title: "How Big Is Infinity? — Cantor's Diagonalization",
    channel: '3Blue1Brown',
    durationSec: 1098,
    category: 'math',
    thumbnailGradient: 'from-blue-800 via-cyan-700 to-teal-600',
    aiScore: 98,
    aiReasoning: "Cantors Theorem durch Animation erklärt — macht das Überabzählbare greifbar.",
    saved: true,
    seen: false,
  },
  {
    videoId: 'v013',
    title: 'Atomic Habits — The Science Behind Behavior Change',
    channel: 'Kurzgesagt',
    durationSec: 776,
    category: 'science',
    thumbnailGradient: 'from-orange-800 via-red-700 to-rose-700',
    aiScore: 80,
    aiReasoning: 'Gut belegte Neurowissenschaft der Gewohnheitsbildung — leicht werbend, aber solider Kern.',
    saved: false,
    seen: true,
  },
  {
    videoId: 'v014',
    title: 'Thermodynamics and the Arrow of Time',
    channel: 'Vsauce',
    durationSec: 1621,
    category: 'science',
    thumbnailGradient: 'from-zinc-800 via-neutral-700 to-stone-600',
    aiScore: 93,
    aiReasoning: 'Entropie ohne Vereinfachung erklärt — verbindet Physik und Philosophie mit ungewöhnlicher intellektueller Ehrlichkeit.',
    saved: false,
    seen: false,
  },
  {
    videoId: 'v015',
    title: 'Linear Algebra and Why Matrices Make Sense',
    channel: 'Khan Academy',
    durationSec: 1402,
    category: 'math',
    thumbnailGradient: 'from-emerald-800 via-green-700 to-lime-600',
    aiScore: 87,
    aiReasoning: 'Geometrische Intuition für Matrizenoperationen — füllt eine Lücke, die die meisten Lehrbücher ignorieren.',
    saved: true,
    seen: true,
  },
]

// ─── All 12 searchable channels ──────────────────────────────────────────────

export const allChannels: MockChannel[] = [
  {
    id: 'ch001',
    name: '3Blue1Brown',
    handle: '@3blue1brown',
    subscribers: '6.1M',
    totalVideos: 142,
    approved: 138,
    rejected: 4,
    diskMB: 2340,
    category: 'math',
    accentColor: '#3B82F6',
    description: 'Mathematik, Animation',
  },
  {
    id: 'ch002',
    name: 'SpongeLore',
    handle: '@spongelore',
    subscribers: '320K',
    totalVideos: 67,
    approved: 51,
    rejected: 16,
    diskMB: 890,
    category: 'society',
    accentColor: '#06B6D4',
    description: 'Popkultur, Gesellschaft',
  },
  {
    id: 'ch003',
    name: 'Kurzgesagt',
    handle: '@kurzgesagt',
    subscribers: '22.4M',
    totalVideos: 198,
    approved: 182,
    rejected: 16,
    diskMB: 3120,
    category: 'science',
    accentColor: '#F59E0B',
    description: 'Wissenschaft, Animation',
  },
  {
    id: 'ch004',
    name: 'Khan Academy',
    handle: '@khanacademy',
    subscribers: '8.7M',
    totalVideos: 1204,
    approved: 1198,
    rejected: 6,
    diskMB: 18200,
    category: 'math',
    accentColor: '#10B981',
    description: 'Mathematik, Lernvideos',
  },
  {
    id: 'ch005',
    name: 'CGP Grey',
    handle: '@cgpgrey',
    subscribers: '5.9M',
    totalVideos: 89,
    approved: 86,
    rejected: 3,
    diskMB: 1560,
    category: 'society',
    accentColor: '#EF4444',
    description: 'Gesellschaft, Geografie',
  },
  {
    id: 'ch006',
    name: 'Vsauce',
    handle: '@vsauce',
    subscribers: '21.8M',
    totalVideos: 234,
    approved: 201,
    rejected: 33,
    diskMB: 4780,
    category: 'science',
    accentColor: '#8B5CF6',
    description: 'Wissenschaft, Philosophie',
  },
  {
    id: 'ch007',
    name: 'Veritasium',
    handle: '@veritasium',
    subscribers: '14.2M',
    totalVideos: 176,
    approved: 159,
    rejected: 17,
    diskMB: 3980,
    category: 'science',
    accentColor: '#EC4899',
    description: 'Physik, Technik',
  },
  {
    id: 'ch008',
    name: 'TED-Ed',
    handle: '@teded',
    subscribers: '18.9M',
    totalVideos: 1842,
    approved: 1701,
    rejected: 141,
    diskMB: 24300,
    category: 'science',
    accentColor: '#EF4444',
    description: 'Bildung, Animation',
  },
  {
    id: 'ch009',
    name: 'Crash Course',
    handle: '@crashcourse',
    subscribers: '15.3M',
    totalVideos: 2103,
    approved: 1890,
    rejected: 213,
    diskMB: 31200,
    category: 'history',
    accentColor: '#06B6D4',
    description: 'Geschichte, Wissenschaft',
  },
  {
    id: 'ch010',
    name: 'SciShow',
    handle: '@scishow',
    subscribers: '7.4M',
    totalVideos: 3412,
    approved: 2890,
    rejected: 522,
    diskMB: 41500,
    category: 'science',
    accentColor: '#F97316',
    description: 'Wissenschaft, Kuriositäten',
  },
  {
    id: 'ch011',
    name: 'Numberphile',
    handle: '@numberphile',
    subscribers: '4.6M',
    totalVideos: 498,
    approved: 481,
    rejected: 17,
    diskMB: 6200,
    category: 'math',
    accentColor: '#F59E0B',
    description: 'Mathematik, Zahlen',
  },
  {
    id: 'ch012',
    name: 'Computerphile',
    handle: '@computerphile',
    subscribers: '2.1M',
    totalVideos: 387,
    approved: 361,
    rejected: 26,
    diskMB: 4900,
    category: 'tech',
    accentColor: '#6366F1',
    description: 'Informatik, Algorithmen',
  },
]

// Keep legacy export for compatibility
export const mockChannels = allChannels.slice(0, 6)

// ─── Rejected Videos (20) ────────────────────────────────────────────────────

export const rejectedVideos: MockRejectedVideo[] = [
  {
    videoId: 'r001',
    title: '10 Signs You Are A GENIUS (Number 7 Will Shock You)',
    channel: 'BrainHacks',
    durationSec: 487,
    category: 'science',
    thumbnailGradient: 'from-red-900 via-red-700 to-orange-600',
    aiScore: 12,
    aiReasoning: 'Clickbait-Titel ohne wissenschaftliche Grundlage. Listicle-Format mit leeren Behauptungen.',
    clickbaitScore: 9,
    manipulationScore: 7,
  },
  {
    videoId: 'r002',
    title: 'I Found The SECRET To Getting Rich in 2024',
    channel: 'MoneyMind',
    durationSec: 1102,
    category: 'society',
    thumbnailGradient: 'from-yellow-800 via-amber-700 to-yellow-600',
    aiScore: 8,
    aiReasoning: 'Finanzieller Clickbait ohne Substanz. Fördert unrealistische Erwartungen.',
    clickbaitScore: 10,
    manipulationScore: 9,
  },
  {
    videoId: 'r003',
    title: 'Scientists Are HIDING This From You About Space',
    channel: 'TruthSeeker99',
    durationSec: 743,
    category: 'science',
    thumbnailGradient: 'from-indigo-900 via-purple-800 to-violet-700',
    aiScore: 6,
    aiReasoning: 'Verschwörungsframing. Keine Quellen, falsche Dringlichkeit, wissenschaftsfeindlich.',
    clickbaitScore: 9,
    manipulationScore: 10,
  },
  {
    videoId: 'r004',
    title: 'My GIRLFRIEND Reacts to Quantum Physics (EMOTIONAL)',
    channel: 'ReactKing',
    durationSec: 1820,
    category: 'science',
    thumbnailGradient: 'from-pink-800 via-rose-700 to-red-600',
    aiScore: 19,
    aiReasoning: 'Reaktionsformat ohne Lernwert. Quantenphysik als Prop für emotionalen Thumbnail-Bait.',
    clickbaitScore: 8,
    manipulationScore: 6,
  },
  {
    videoId: 'r005',
    title: 'You Have Been Eating Pizza WRONG Your Whole Life',
    channel: 'LifeHacksPro',
    durationSec: 312,
    category: 'society',
    thumbnailGradient: 'from-orange-700 via-red-600 to-rose-500',
    aiScore: 22,
    aiReasoning: 'Trivialer Tipp mit dramatischer Übertreibung. Kein substantieller Lernwert.',
    clickbaitScore: 8,
    manipulationScore: 5,
  },
  {
    videoId: 'r006',
    title: 'Why I Quit My 500K Job To Do THIS',
    channel: 'LifeCoach Dave',
    durationSec: 1432,
    category: 'society',
    thumbnailGradient: 'from-sky-800 via-blue-700 to-indigo-600',
    aiScore: 31,
    aiReasoning: 'Persönliche Anekdote ohne übertragbaren Lerninhalt. Motivations-Infotainment.',
    clickbaitScore: 7,
    manipulationScore: 6,
  },
  {
    videoId: 'r007',
    title: 'Scientists Discover SCARY New Organism Under Antarctica',
    channel: 'ScienceShock',
    durationSec: 689,
    category: 'science',
    thumbnailGradient: 'from-teal-900 via-cyan-800 to-sky-700',
    aiScore: 35,
    aiReasoning: 'Übertriebenes Framing realer Forschung. Sensationspresse, nicht Wissenschaftskommunikation.',
    clickbaitScore: 8,
    manipulationScore: 5,
  },
  {
    videoId: 'r008',
    title: 'This ONE Habit Changed My Life Forever (MUST WATCH)',
    channel: 'OptimizeYou',
    durationSec: 892,
    category: 'society',
    thumbnailGradient: 'from-violet-800 via-purple-700 to-fuchsia-600',
    aiScore: 28,
    aiReasoning: 'Anekdotische Selbsthilfe ohne Evidenz. Emotionale Überzeugung statt Information.',
    clickbaitScore: 7,
    manipulationScore: 8,
  },
  {
    videoId: 'r009',
    title: 'EXPOSED: The TRUTH About Vitamins Big Pharma Hides',
    channel: 'NaturalCureTV',
    durationSec: 1243,
    category: 'science',
    thumbnailGradient: 'from-green-900 via-emerald-800 to-teal-700',
    aiScore: 4,
    aiReasoning: 'Medizinische Fehlinformation. Verschwörungsrhetorik gegen Pharmaindustrie.',
    clickbaitScore: 9,
    manipulationScore: 10,
  },
  {
    videoId: 'r010',
    title: 'I Tried 30 Productivity Apps So You Don\'t Have To',
    channel: 'AppReviewr',
    durationSec: 2102,
    category: 'tech',
    thumbnailGradient: 'from-slate-800 via-gray-700 to-zinc-600',
    aiScore: 42,
    aiReasoning: 'Oberflächliche App-Reviews als Filler. Zu lang, zu wenig Tiefe, teilweise gesponsert.',
    clickbaitScore: 4,
    manipulationScore: 3,
  },
  {
    videoId: 'r011',
    title: 'Why Humans Can\'t Actually Think (Neuroscience PROOF)',
    channel: 'MindBlown',
    durationSec: 761,
    category: 'science',
    thumbnailGradient: 'from-amber-900 via-orange-800 to-yellow-700',
    aiScore: 24,
    aiReasoning: 'Neurowissenschaft falsch dargestellt zur Provokation. Reißerischer Titel, schwache Argumentation.',
    clickbaitScore: 8,
    manipulationScore: 7,
  },
  {
    videoId: 'r012',
    title: 'AI Will REPLACE You (Unless You Watch This Video)',
    channel: 'FuturePanic',
    durationSec: 1087,
    category: 'tech',
    thumbnailGradient: 'from-red-900 via-rose-800 to-pink-700',
    aiScore: 18,
    aiReasoning: 'Angst als Klick-Trigger. Keine konkreten Handlungsempfehlungen, nur vage Bedrohung.',
    clickbaitScore: 9,
    manipulationScore: 9,
  },
  {
    videoId: 'r013',
    title: 'The Matrix Is REAL and Here\'s How to Escape It',
    channel: 'WokePhilosophy',
    durationSec: 1334,
    category: 'philosophy',
    thumbnailGradient: 'from-green-900 via-lime-800 to-emerald-700',
    aiScore: 29,
    aiReasoning: 'Popphilosophie ohne Substanz. Simulationstheorie als Lebensratgeber-Clickbait.',
    clickbaitScore: 8,
    manipulationScore: 6,
  },
  {
    videoId: 'r014',
    title: 'How I Make $5000/Month With This Simple Trick',
    channel: 'PassiveIncome101',
    durationSec: 934,
    category: 'society',
    thumbnailGradient: 'from-lime-700 via-green-600 to-teal-500',
    aiScore: 9,
    aiReasoning: 'Finanzbetrug-Framing. Unrealistische Einkommensversprechen ohne Transparenz.',
    clickbaitScore: 10,
    manipulationScore: 9,
  },
  {
    videoId: 'r015',
    title: 'Shocking: Camera Catches What Nobody Talks About',
    channel: 'ViralClips',
    durationSec: 298,
    category: 'society',
    thumbnailGradient: 'from-zinc-800 via-neutral-700 to-stone-600',
    aiScore: 5,
    aiReasoning: 'Extremer Clickbait ohne Inhalt. Mysteriöser Titel verbirgt leeres Video.',
    clickbaitScore: 10,
    manipulationScore: 8,
  },
  {
    videoId: 'r016',
    title: 'Why School Makes You DUMB (The Hidden Agenda)',
    channel: 'AntiEstablishment',
    durationSec: 1521,
    category: 'society',
    thumbnailGradient: 'from-indigo-800 via-blue-700 to-sky-600',
    aiScore: 33,
    aiReasoning: 'Bildungskritik ohne Evidenz. Verschwörungsdenken als Schul-Rage-Bait.',
    clickbaitScore: 8,
    manipulationScore: 7,
  },
  {
    videoId: 'r017',
    title: 'I Let AI Plan My Entire Week (Surprisingly Emotional)',
    channel: 'TechVlogger',
    durationSec: 1243,
    category: 'tech',
    thumbnailGradient: 'from-purple-800 via-violet-700 to-indigo-600',
    aiScore: 38,
    aiReasoning: 'Vlog ohne Lernwert. KI-Tool als emotionaler Storytelling-Prop.',
    clickbaitScore: 6,
    manipulationScore: 5,
  },
  {
    videoId: 'r018',
    title: 'The Ancient Technique That Will Double Your Memory',
    channel: 'BrainBoost',
    durationSec: 876,
    category: 'science',
    thumbnailGradient: 'from-teal-800 via-cyan-700 to-sky-600',
    aiScore: 41,
    aiReasoning: 'Gedächtnistechniken überbewertet dargestellt. Methode ok, Versprechen überzogen.',
    clickbaitScore: 7,
    manipulationScore: 4,
  },
  {
    videoId: 'r019',
    title: 'Dark Psychology: 7 Ways People Control You',
    channel: 'PsychSecrets',
    durationSec: 1102,
    category: 'philosophy',
    thumbnailGradient: 'from-gray-900 via-zinc-800 to-neutral-700',
    aiScore: 26,
    aiReasoning: 'Pseudo-Psychologie als Sensation. Listicle mit sensationellen Etiketten statt Analyse.',
    clickbaitScore: 8,
    manipulationScore: 8,
  },
  {
    videoId: 'r020',
    title: 'ChatGPT Just Changed EVERYTHING (Watch Before Deleted)',
    channel: 'AINewsNow',
    durationSec: 687,
    category: 'tech',
    thumbnailGradient: 'from-sky-900 via-blue-800 to-indigo-700',
    aiScore: 15,
    aiReasoning: 'Maximale FOMO-Rhetorik. Kein konkreter Inhalt, reine Clickbait-Konstruktion.',
    clickbaitScore: 10,
    manipulationScore: 9,
  },
]

// ─── SponsorBlock Categories (10) ───────────────────────────────────────────

export const sponsorBlockCategories: SponsorBlockCategory[] = [
  {
    key: 'sponsor',
    label: 'Sponsor',
    labelDe: 'Sponsor',
    color: '#00D400',
    defaultBehavior: 'auto',
    description: 'Bezahlte Produktwerbung',
    exampleSkips: 67,
    timeSavedMin: 42,
  },
  {
    key: 'selfpromo',
    label: 'Self-Promotion',
    labelDe: 'Eigenwerbung',
    color: '#FFFF00',
    defaultBehavior: 'auto',
    description: 'Werbung für eigene Produkte',
    exampleSkips: 31,
    timeSavedMin: 18,
  },
  {
    key: 'interaction',
    label: 'Interaction Reminder',
    labelDe: 'Interaktions-Erinnerung',
    color: '#CC00FF',
    defaultBehavior: 'ignore',
    description: 'Like/Abo-Aufforderungen',
    exampleSkips: 0,
    timeSavedMin: 0,
  },
  {
    key: 'intro',
    label: 'Intro',
    labelDe: 'Intro',
    color: '#00FFFF',
    defaultBehavior: 'auto',
    description: 'Kanal-Intro / Jingle',
    exampleSkips: 28,
    timeSavedMin: 14,
  },
  {
    key: 'outro',
    label: 'Outro/Credits',
    labelDe: 'Outro / Abspann',
    color: '#0202ED',
    defaultBehavior: 'auto',
    description: 'Abspann und Endcards',
    exampleSkips: 24,
    timeSavedMin: 22,
  },
  {
    key: 'preview',
    label: 'Preview/Recap',
    labelDe: 'Vorschau / Rückblick',
    color: '#008FD6',
    defaultBehavior: 'manual',
    description: 'Inhaltsvorschau am Anfang',
    exampleSkips: 11,
    timeSavedMin: 9,
  },
  {
    key: 'hook',
    label: 'Hook/Teaser',
    labelDe: 'Hook / Teaser',
    color: '#FF9900',
    defaultBehavior: 'ignore',
    description: 'Emotionaler Einstieg-Teaser',
    exampleSkips: 0,
    timeSavedMin: 0,
  },
  {
    key: 'filler',
    label: 'Filler Tangent',
    labelDe: 'Filler / Abschweifung',
    color: '#7300FF',
    defaultBehavior: 'manual',
    description: 'Themenfremde Abschnitte',
    exampleSkips: 7,
    timeSavedMin: 8,
  },
  {
    key: 'music_offtopic',
    label: 'Non-Music Off-Topic',
    labelDe: 'Off-Topic Musik',
    color: '#FF9900',
    defaultBehavior: 'ignore',
    description: 'Musik ohne thematischen Bezug',
    exampleSkips: 0,
    timeSavedMin: 0,
  },
  {
    key: 'poi_highlight',
    label: 'Highlight',
    labelDe: 'Highlight',
    color: '#FF1684',
    defaultBehavior: 'ignore',
    description: 'Markierte Schlüsselstellen',
    exampleSkips: 3,
    timeSavedMin: 3,
  },
]

export const sponsorBlockStats = {
  totalSkipped: 171,
  timeSaved: '2h 56min',
  topCategory: 'sponsor',
}

export const mockSeries: MockSeries[] = [
  {
    id: 's001',
    title: 'Deep Learning',
    description: 'Eine Reise durch die Grundlagen und Fortgeschrittenen-Themen der Neuronalen Netze.',
    thumbnailGradient: 'from-blue-900 via-indigo-800 to-blue-600',
    category: 'math',
  },
  {
    id: 's002',
    title: 'SpongeBob Wirtschaft',
    description: 'Warum Bikini Bottom dem Untergang geweiht ist und andere soziologische Analysen.',
    thumbnailGradient: 'from-yellow-600 via-amber-500 to-orange-400',
    category: 'society',
  },
]
